--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MilkAndCookiz/PortableChests
build-by-default: true
branches:
- main
projects:
  PortableChest:
    path: PortableChest/
    icon: "icon.png"
...
